### ISSUE TITLE
Doesn't able to run the application file?

### ISSUE THREAD

**Issue by neophyteCoder0** [lw222gz/2dv515-webscraper#1]
I am trying to run your program and found that it's asking for root.page, category, dataset.dir. Could you suggest How to and where to set them up? I am a beginner and learning web scrapping in Java through your contribution. Big thanks for your code contribution.

**Comment by lw222gz** [comment]
Hi, yea I can set up a readme right now (sorry for a late response). However I should mention that this was made for a course where we needed to scrape a dataset specifically from wikipedia to then use the generated dataset for a search engine application. No further work is planned to be done so if you wanna modify, feel free to fork the repo.
